set_property SRC_FILE_INFO {cfile:/home/user/elettronica_base/labs/lab8/lab8.srcs/constrs_1/imports/xilinx/Arty-A7-35-Master.xdc rfile:../../../lab8.srcs/constrs_1/imports/xilinx/Arty-A7-35-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { sys_clock }]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { pwm_out_0 }]; #IO_L24N_T3_35 Sch=led[4]
