#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jan 08 15:24:22 CET 2026
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_lab7_behav -key {Behavioral:sim_1:Functional:tb_lab7} -tclbatch tb_lab7.tcl -protoinst "protoinst_files/lab7_block_design.protoinst" -view /home/user/elettronica_base/labs/lab7/tb_lab7_behav.wcfg -log simulate.log"
xsim tb_lab7_behav -key {Behavioral:sim_1:Functional:tb_lab7} -tclbatch tb_lab7.tcl -protoinst "protoinst_files/lab7_block_design.protoinst" -view /home/user/elettronica_base/labs/lab7/tb_lab7_behav.wcfg -log simulate.log

