# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xilinx/Arty-A7-35-Master.xdc

# Block Designs: bd/lab7_block_design/lab7_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_block_design || ORIG_REF_NAME==lab7_block_design} -quiet] -quiet

# IP: bd/lab7_block_design/ip/lab7_block_design_dds_compiler_0_0/lab7_block_design_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_block_design_dds_compiler_0_0 || ORIG_REF_NAME==lab7_block_design_dds_compiler_0_0} -quiet] -quiet

# IP: bd/lab7_block_design/ip/lab7_block_design_dds_compiler_0_1/lab7_block_design_dds_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_block_design_dds_compiler_0_1 || ORIG_REF_NAME==lab7_block_design_dds_compiler_0_1} -quiet] -quiet

# IP: bd/lab7_block_design/ip/lab7_block_design_clk_wiz_0_0/lab7_block_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_block_design_clk_wiz_0_0 || ORIG_REF_NAME==lab7_block_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/lab7_block_design/ip/lab7_block_design_c_addsub_0_0/lab7_block_design_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_block_design_c_addsub_0_0 || ORIG_REF_NAME==lab7_block_design_c_addsub_0_0} -quiet] -quiet

# IP: bd/lab7_block_design/ip/lab7_block_design_ila_0_0/lab7_block_design_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_block_design_ila_0_0 || ORIG_REF_NAME==lab7_block_design_ila_0_0} -quiet] -quiet

# IP: bd/lab7_block_design/ip/lab7_block_design_FIR_0_0/lab7_block_design_FIR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_block_design_FIR_0_0 || ORIG_REF_NAME==lab7_block_design_FIR_0_0} -quiet] -quiet

# XDC: /home/user/elettronica_base/labs/lab7/lab7.gen/sources_1/bd/lab7_block_design/lab7_block_design_ooc.xdc
