#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2_AR000035739 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 21 17:27:29 CET 2026
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim T20_FiniteStateMachineTb_behav -key {Behavioral:sim_1:Functional:T20_FiniteStateMachineTb} -tclbatch T20_FiniteStateMachineTb.tcl -view /home/user/elettronica_base/labs/lab9/T20_FiniteStateMachineTb_behav.wcfg -log simulate.log"
xsim T20_FiniteStateMachineTb_behav -key {Behavioral:sim_1:Functional:T20_FiniteStateMachineTb} -tclbatch T20_FiniteStateMachineTb.tcl -view /home/user/elettronica_base/labs/lab9/T20_FiniteStateMachineTb_behav.wcfg -log simulate.log

