# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/elettronica_base/labs/lab7/lab7.srcs/sources_1/bd/lab7_block_design/ip/lab7_block_design_dds_compiler_0_1/lab7_block_design_dds_compiler_0_1.xci
# IP: The module: 'lab7_block_design_dds_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/elettronica_base/labs/lab7/lab7.gen/sources_1/bd/lab7_block_design/ip/lab7_block_design_dds_compiler_0_1/lab7_block_design_dds_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_block_design_dds_compiler_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/elettronica_base/labs/lab7/lab7.srcs/sources_1/bd/lab7_block_design/ip/lab7_block_design_dds_compiler_0_1/lab7_block_design_dds_compiler_0_1.xci
# IP: The module: 'lab7_block_design_dds_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/elettronica_base/labs/lab7/lab7.gen/sources_1/bd/lab7_block_design/ip/lab7_block_design_dds_compiler_0_1/lab7_block_design_dds_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_block_design_dds_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
