# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/elettronica_base/labs/lab8/lab8.srcs/sources_1/bd/lab8_block_design/ip/lab8_block_design_ila_0_0/lab8_block_design_ila_0_0.xci
# IP: The module: 'lab8_block_design_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/elettronica_base/labs/lab8/lab8.gen/sources_1/bd/lab8_block_design/ip/lab8_block_design_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab8_block_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/elettronica_base/labs/lab8/lab8.gen/sources_1/bd/lab8_block_design/ip/lab8_block_design_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab8_block_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/elettronica_base/labs/lab8/lab8.gen/sources_1/bd/lab8_block_design/ip/lab8_block_design_ila_0_0/lab8_block_design_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab8_block_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user/elettronica_base/labs/lab8/lab8.srcs/sources_1/bd/lab8_block_design/ip/lab8_block_design_ila_0_0/lab8_block_design_ila_0_0.xci
# IP: The module: 'lab8_block_design_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/elettronica_base/labs/lab8/lab8.gen/sources_1/bd/lab8_block_design/ip/lab8_block_design_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab8_block_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/elettronica_base/labs/lab8/lab8.gen/sources_1/bd/lab8_block_design/ip/lab8_block_design_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab8_block_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user/elettronica_base/labs/lab8/lab8.gen/sources_1/bd/lab8_block_design/ip/lab8_block_design_ila_0_0/lab8_block_design_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab8_block_design_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
