# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xilinx/Arty-A7-35-Master.xdc

# Block Designs: bd/lab8_block_design/lab8_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab8_block_design || ORIG_REF_NAME==lab8_block_design} -quiet] -quiet

# IP: bd/lab8_block_design/ip/lab8_block_design_dist_mem_gen_0_0/lab8_block_design_dist_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab8_block_design_dist_mem_gen_0_0 || ORIG_REF_NAME==lab8_block_design_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/lab8_block_design/ip/lab8_block_design_c_counter_binary_0_0/lab8_block_design_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab8_block_design_c_counter_binary_0_0 || ORIG_REF_NAME==lab8_block_design_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/lab8_block_design/ip/lab8_block_design_ila_0_0/lab8_block_design_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab8_block_design_ila_0_0 || ORIG_REF_NAME==lab8_block_design_ila_0_0} -quiet] -quiet

# IP: bd/lab8_block_design/ip/lab8_block_design_clk_wiz_0_0/lab8_block_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab8_block_design_clk_wiz_0_0 || ORIG_REF_NAME==lab8_block_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/lab8_block_design/ip/lab8_block_design_pwm_0_0/lab8_block_design_pwm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab8_block_design_pwm_0_0 || ORIG_REF_NAME==lab8_block_design_pwm_0_0} -quiet] -quiet

# IP: bd/lab8_block_design/ip/lab8_block_design_util_vector_logic_0_0/lab8_block_design_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab8_block_design_util_vector_logic_0_0 || ORIG_REF_NAME==lab8_block_design_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/lab8_block_design/ip/lab8_block_design_TickCounter_0_0/lab8_block_design_TickCounter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab8_block_design_TickCounter_0_0 || ORIG_REF_NAME==lab8_block_design_TickCounter_0_0} -quiet] -quiet

# XDC: /home/user/elettronica_base/labs/lab8/lab8.gen/sources_1/bd/lab8_block_design/lab8_block_design_ooc.xdc
